# Management configuration
server.port=${MANAGEMENT_PORT:9191}
management.endpoints.web.exposure.include=health

# Database configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Logging configuration
# logging.level.org.springframework.jdbc.core=trace
